import React, { useState, useEffect } from "react";
import MapComponent from "./MapComponent";
import SceneComponent from "./SceneComponent";
import ImpactReport from "./ImpactReport";
import Tooltip from "./Tooltip"; // Import the new component
import {
  calculateImpactEnergy,
  calculateCraterDiameter,
  calculateSeismicMagnitude,
} from "./utils/physics";
import "./App.css";
import "./Tooltip.css"; // Import the tooltip styles

// Tooltip text constants
const tooltipContent = {
  diameter:
    "The average estimated diameter of the asteroid in meters. Larger asteroids carry significantly more kinetic energy.",
  velocity:
    "The speed at which the asteroid is traveling relative to Earth in kilometers per second. Velocity is a major factor in impact energy (E = ½mv²).",
  missDistance:
    "The closest distance the asteroid will pass by Earth. A smaller value indicates a higher risk of collision.",
  approachDate:
    "The date when the asteroid will make its closest approach to Earth.",
  semiMajorAxis:
    "Half of the longest diameter of the asteroid's elliptical orbit, measured in Astronomical Units (AU). It defines the average size of the orbit.",
  eccentricity:
    "A value from 0 to 1 that measures how much the asteroid's orbit deviates from a perfect circle. 0 is a circle, and approaching 1 is a very elongated ellipse.",
  inclination:
    "The angle between the asteroid's orbital plane and Earth's orbital plane (the ecliptic), measured in degrees.",
  impactEnergy:
    "The kinetic energy released upon impact, measured in Megatons of TNT. This is the primary driver of the impact's destructive power.",
  craterDiameter:
    "The estimated diameter of the crater formed by a land impact, based on the impact energy and target surface properties.",
  seismicMagnitude:
    "The equivalent magnitude on the Richter scale for the earthquake generated by the impact's seismic waves.",
  impulse:
    "A change in velocity ('delta-v') applied to the asteroid, measured in meters per second. Even a small change applied far in advance can significantly alter its trajectory.",
};

function App() {
  const [asteroids, setAsteroids] = useState([]);
  const [selectedAsteroidId, setSelectedAsteroidId] = useState("");
  const [details, setDetails] = useState(null);
  const [mode, setMode] = useState("preset");
  const [customParams, setCustomParams] = useState({
    diameter: 100,
    velocity: 20,
  });
  const [simResults, setSimResults] = useState(null);
  const [mitigation, setMitigation] = useState({
    isActive: false,
    velocityChange: 0,
  });
  const [impactPosition, setImpactPosition] = useState({
    lat: 20.5937,
    lng: 78.9629,
  });
  const [impactOccurred, setImpactOccurred] = useState(false);
  const [isOceanImpact, setIsOceanImpact] = useState(false);

  useEffect(() => {
    fetch("http://localhost:5000/api/neos")
      .then((res) => res.json())
      .then((data) => setAsteroids(data))
      .catch((err) => console.error("Could not fetch asteroid list.", err));
  }, []);

  useEffect(() => {
    if (mode !== "preset" || !selectedAsteroidId) {
      setDetails(null);
      setSimResults(null);
      setImpactOccurred(false);
      setMitigation({ isActive: false, velocityChange: 0 });
      return;
    }
    fetch(`http://localhost:5000/api/neo/${selectedAsteroidId}`)
      .then((res) => res.json())
      .then((data) => {
        setDetails(data);
        setSimResults(null); // Clear previous simulation results
        setImpactOccurred(false);
        setMitigation({ isActive: false, velocityChange: 0 });
      })
      .catch((err) => console.error("Could not fetch details.", err));
  }, [selectedAsteroidId, mode]);

  const handleCustomParamChange = (e) => {
    setCustomParams({ ...customParams, [e.target.name]: e.target.value });
  };

  const handleSimulate = () => {
    setImpactOccurred(false);
    let diameter, velocity;
    if (mode === "preset" && details) {
      diameter = details.estimated_diameter.meters.estimated_diameter_max;
      velocity =
        details.close_approach_data[0].relative_velocity.kilometers_per_second;
    } else {
      diameter = customParams.diameter;
      velocity = customParams.velocity;
    }
    const energy = calculateImpactEnergy(diameter, velocity);
    const craterDiameterKm = calculateCraterDiameter(energy.joules);
    const seismicMagnitude = calculateSeismicMagnitude(energy.joules);

    setSimResults({
      energyMegatons: energy.megatons,
      craterDiameterKm,
      seismicMagnitude,
    });
    setMitigation({ isActive: true, velocityChange: 0 });
  };

  const handleMitigationChange = (e) => {
    setMitigation({
      ...mitigation,
      velocityChange: parseFloat(e.target.value),
    });
  };

  const handleImpact = () => {
    setImpactOccurred(true);
  };

  const closeApproachData = details?.close_approach_data?.[0];
  const orbitalData = details?.orbital_data;

  return (
    <div className="App">
      <header className="App-header">
        <h1>AstroStrike Simulator ☄️</h1>
        <p>
          A data-driven tool for modeling asteroid impact scenarios,
          consequences, and mitigation strategies.
        </p>
      </header>

      <div className="controls-container">
        <div className="mode-selector">
          <label>
            <input
              type="radio"
              value="preset"
              checked={mode === "preset"}
              onChange={() => setMode("preset")}
            />{" "}
            Select Real NEO
          </label>
          <label>
            <input
              type="radio"
              value="custom"
              checked={mode === "custom"}
              onChange={() => setMode("custom")}
            />{" "}
            Create Custom Scenario
          </label>
        </div>
        {mode === "preset" ? (
          <select
            onChange={(e) => setSelectedAsteroidId(e.target.value)}
            value={selectedAsteroidId}
            className="asteroid-select"
          >
            <option value="">-- Select an Asteroid --</option>
            {asteroids.map((ast) => (
              <option key={ast.id} value={ast.id}>
                {ast.name}
              </option>
            ))}
          </select>
        ) : (
          <div className="custom-params">
            <label>
              Diameter (m):
              <input
                type="number"
                name="diameter"
                value={customParams.diameter}
                onChange={handleCustomParamChange}
              />
            </label>
            <label>
              Velocity (km/s):
              <input
                type="number"
                name="velocity"
                value={customParams.velocity}
                onChange={handleCustomParamChange}
              />
            </label>
          </div>
        )}
        <button onClick={handleSimulate} className="simulate-button">
          Simulate Impact
        </button>
      </div>

      <div className="main-content">
        {/* NEW SECTION for displaying asteroid parameters */}
        {details && mode === "preset" && (
          <div className="details-section parameter-section">
            <div className="parameters-grid">
              <div className="params-column">
                <h3>Event Parameters</h3>
                <p>
                  <Tooltip text={tooltipContent.diameter}>
                    <strong>Diameter:</strong>{" "}
                    {Number(
                      details.estimated_diameter.meters.estimated_diameter_max
                    ).toFixed(0)}{" "}
                    m
                  </Tooltip>
                </p>
                <p>
                  <Tooltip text={tooltipContent.velocity}>
                    <strong>Velocity:</strong>{" "}
                    {Number(
                      closeApproachData?.relative_velocity.kilometers_per_second
                    ).toFixed(2)}{" "}
                    km/s
                  </Tooltip>
                </p>
                <p>
                  <Tooltip text={tooltipContent.missDistance}>
                    <strong>Miss Distance:</strong>{" "}
                    {Number(
                      closeApproachData?.miss_distance.kilometers
                    ).toLocaleString("en-US", {
                      maximumFractionDigits: 0,
                    })}{" "}
                    km
                  </Tooltip>
                </p>
                <p>
                  <Tooltip text={tooltipContent.approachDate}>
                    <strong>Approach Date:</strong>{" "}
                    {closeApproachData?.close_approach_date}
                  </Tooltip>
                </p>
              </div>
              <div className="params-column">
                <h3>Orbital Parameters</h3>
                <p>
                  <Tooltip text={tooltipContent.semiMajorAxis}>
                    <strong>Semi-Major Axis:</strong>{" "}
                    {Number(orbitalData?.semi_major_axis).toFixed(2)} AU
                  </Tooltip>
                </p>
                <p>
                  <Tooltip text={tooltipContent.eccentricity}>
                    <strong>Eccentricity:</strong>{" "}
                    {Number(orbitalData?.eccentricity).toFixed(3)}
                  </Tooltip>
                </p>
                <p>
                  <Tooltip text={tooltipContent.inclination}>
                    <strong>Inclination:</strong>{" "}
                    {Number(orbitalData?.inclination).toFixed(3)}°
                  </Tooltip>
                </p>
              </div>
            </div>
          </div>
        )}

        {simResults && (
          <div className="results-section">
            <h2>Initial Conditions & Potential Effects</h2>
            <div className="details-grid">
              <p>
                <Tooltip text={tooltipContent.impactEnergy}>
                  <strong>Impact Energy:</strong>{" "}
                  {simResults.energyMegatons.toFixed(2)} Megatons TNT
                </Tooltip>
              </p>
              <p>
                <Tooltip text={tooltipContent.craterDiameter}>
                  <strong>Crater Diameter:</strong>{" "}
                  {simResults.craterDiameterKm.toFixed(2)} km
                </Tooltip>
              </p>
              <p>
                <Tooltip text={tooltipContent.seismicMagnitude}>
                  <strong>Seismic Magnitude:</strong>{" "}
                  {simResults.seismicMagnitude.toFixed(2)} (Richter Scale)
                </Tooltip>
              </p>
            </div>
            <div className="ocean-impact-toggle">
              <label>
                <input
                  type="checkbox"
                  checked={isOceanImpact}
                  onChange={(e) => setIsOceanImpact(e.target.checked)}
                />
                Simulate as Ocean Impact (for Tsunami Analysis)
              </label>
            </div>
          </div>
        )}

        {impactOccurred && simResults && (
          <ImpactReport
            simResults={simResults}
            impactPosition={impactPosition}
            isOceanImpact={isOceanImpact}
          />
        )}

        {mitigation.isActive && (
          <div className="mitigation-section">
            <h2>🌍 Planetary Defense Center</h2>
            <p>
              Apply an impulse to deflect the asteroid. The orbit will update in
              real-time based on gravitational physics.
            </p>
            <label>
              <Tooltip text={tooltipContent.impulse}>
                Impulse (Δv m/s): {mitigation.velocityChange}
              </Tooltip>
              <input
                type="range"
                name="velocityChange"
                min="0"
                max="100"
                step="0.1"
                value={mitigation.velocityChange}
                onChange={handleMitigationChange}
              />
            </label>
            <p
              style={{
                color: impactOccurred ? "#e94560" : "#28a745",
                fontWeight: "bold",
                fontSize: "1.2em",
              }}
            >
              SIMULATION STATUS:{" "}
              {impactOccurred
                ? "IMPACT DETECTED!"
                : "COURSE IS CLEAR... FOR NOW."}
            </p>
          </div>
        )}

        <div id="visuals-section" className="visuals-section">
          <MapComponent
            simResults={simResults}
            impactPosition={impactPosition}
            setImpactPosition={setImpactPosition}
            isHit={impactOccurred}
            isOceanImpact={isOceanImpact}
          />
          <div className="scene-container">
            {mitigation.isActive && (
              <SceneComponent
                details={details}
                customParams={customParams}
                mode={mode}
                mitigation={mitigation}
                onImpact={handleImpact}
              />
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
